import Head from 'next/head'
import Image from 'next/image'
import HomeBanner from '../components/Pages/Home/Banner'
import BecomeInstructor from '../components/Pages/Home/BecomeInstructor'
import ExploreCourses from '../components/Pages/Home/ExploreCourses'
import LearnFromComfortZoneSection from '../components/Pages/Home/LearnFromComfortZone'
import RecordedCourses from '../components/Pages/Home/RecordedCourses'
import Reviews from '../components/Pages/Home/Reviews'
import ShortCourses from '../components/Pages/Home/ShortCourses'
import SkyrocketSection from '../components/Pages/Home/SkyrocketSection'
import "slick-carousel/slick/slick.css"; 
import styles from '../styles/Home.module.css'
// import styles from '../styles/sass/index.scss';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Digital Gurkha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <HomeBanner/>
          <ExploreCourses/>
          <SkyrocketSection/>
          <ShortCourses/>
          <RecordedCourses/>
          <BecomeInstructor/>
          <Reviews/>
          <LearnFromComfortZoneSection/>
      </main>
    </div>
  )
}


Home.layout = "Layout1"
